// Mocks generated by Mockito 5.4.6 from annotations
// in paraclete/test/features/terminal/data/terminal_session_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:paraclete/features/terminal/data/ssh_client.dart' as _i3;
import 'package:paraclete/features/terminal/domain/entities/ssh_connection.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSshConnection_0 extends _i1.SmartFake implements _i2.SshConnection {
  _FakeSshConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SshClientWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSshClientWrapper extends _i1.Mock implements _i3.SshClientWrapper {
  MockSshClientWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SshConnection get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeSshConnection_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.SshConnection);

  @override
  _i3.SshClientState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i3.SshClientState.disconnected,
      ) as _i3.SshClientState);

  @override
  _i4.Stream<String> get outputStream => (super.noSuchMethod(
        Invocation.getter(#outputStream),
        returnValue: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  _i4.Stream<_i3.SshClientState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i4.Stream<_i3.SshClientState>.empty(),
      ) as _i4.Stream<_i3.SshClientState>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> connect({
    required int? terminalWidth,
    required int? terminalHeight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #terminalWidth: terminalWidth,
            #terminalHeight: terminalHeight,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void sendInput(String? data) => super.noSuchMethod(
        Invocation.method(
          #sendInput,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> resize(
    int? width,
    int? height,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resize,
          [
            width,
            height,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> executeCommand(String? command) => (super.noSuchMethod(
        Invocation.method(
          #executeCommand,
          [command],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #executeCommand,
            [command],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
