// Mocks generated by Mockito 5.4.6 from annotations
// in paraclete/test/features/voice/data/datasources/deepgram_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i9;

import 'package:deepgram_speech_to_text/src/deepgram.dart' as _i3;
import 'package:deepgram_speech_to_text/src/types.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:record/src/record.dart' as _i8;
import 'package:record_platform_interface/record_platform_interface.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeepgramSttResult_0 extends _i1.SmartFake
    implements _i2.DeepgramSttResult {
  _FakeDeepgramSttResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeepgramLiveTranscriber_1 extends _i1.SmartFake
    implements _i3.DeepgramLiveTranscriber {
  _FakeDeepgramLiveTranscriber_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeepgramTtsResult_2 extends _i1.SmartFake
    implements _i2.DeepgramTtsResult {
  _FakeDeepgramTtsResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAmplitude_3 extends _i1.SmartFake implements _i4.Amplitude {
  _FakeAmplitude_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Deepgram].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepgram extends _i1.Mock implements _i3.Deepgram {
  MockDeepgram() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i6.Future<_i2.DeepgramSttResult> transcribeFromBytes(
    List<int>? data, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeFromBytes,
          [data],
          {#queryParams: queryParams},
        ),
        returnValue:
            _i6.Future<_i2.DeepgramSttResult>.value(_FakeDeepgramSttResult_0(
          this,
          Invocation.method(
            #transcribeFromBytes,
            [data],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i6.Future<_i2.DeepgramSttResult>);

  @override
  _i6.Future<_i2.DeepgramSttResult> transcribeFromFile(
    _i7.File? file, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeFromFile,
          [file],
          {#queryParams: queryParams},
        ),
        returnValue:
            _i6.Future<_i2.DeepgramSttResult>.value(_FakeDeepgramSttResult_0(
          this,
          Invocation.method(
            #transcribeFromFile,
            [file],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i6.Future<_i2.DeepgramSttResult>);

  @override
  _i6.Future<_i2.DeepgramSttResult> transcribeFromPath(
    String? path, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeFromPath,
          [path],
          {#queryParams: queryParams},
        ),
        returnValue:
            _i6.Future<_i2.DeepgramSttResult>.value(_FakeDeepgramSttResult_0(
          this,
          Invocation.method(
            #transcribeFromPath,
            [path],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i6.Future<_i2.DeepgramSttResult>);

  @override
  _i6.Future<_i2.DeepgramSttResult> transcribeFromUrl(
    String? url, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeFromUrl,
          [url],
          {#queryParams: queryParams},
        ),
        returnValue:
            _i6.Future<_i2.DeepgramSttResult>.value(_FakeDeepgramSttResult_0(
          this,
          Invocation.method(
            #transcribeFromUrl,
            [url],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i6.Future<_i2.DeepgramSttResult>);

  @override
  _i3.DeepgramLiveTranscriber createLiveTranscriber(
    _i6.Stream<List<int>>? audioStream, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLiveTranscriber,
          [audioStream],
          {#queryParams: queryParams},
        ),
        returnValue: _FakeDeepgramLiveTranscriber_1(
          this,
          Invocation.method(
            #createLiveTranscriber,
            [audioStream],
            {#queryParams: queryParams},
          ),
        ),
      ) as _i3.DeepgramLiveTranscriber);

  @override
  _i6.Stream<_i2.DeepgramSttResult> transcribeFromLiveAudioStream(
    _i6.Stream<List<int>>? audioStream, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeFromLiveAudioStream,
          [audioStream],
          {#queryParams: queryParams},
        ),
        returnValue: _i6.Stream<_i2.DeepgramSttResult>.empty(),
      ) as _i6.Stream<_i2.DeepgramSttResult>);

  @override
  _i6.Future<bool> isApiKeyValid() => (super.noSuchMethod(
        Invocation.method(
          #isApiKeyValid,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.DeepgramTtsResult> speakFromText(
    String? text, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #speakFromText,
          [text],
          {#queryParams: queryParams},
        ),
        returnValue:
            _i6.Future<_i2.DeepgramTtsResult>.value(_FakeDeepgramTtsResult_2(
          this,
          Invocation.method(
            #speakFromText,
            [text],
            {#queryParams: queryParams},
          ),
        )),
      ) as _i6.Future<_i2.DeepgramTtsResult>);
}

/// A class which mocks [AudioRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorder extends _i1.Mock implements _i8.AudioRecorder {
  MockAudioRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> start(
    _i4.RecordConfig? config, {
    required String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #start,
          [config],
          {#path: path},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i6.Stream<_i9.Uint8List>> startStream(_i4.RecordConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #startStream,
          [config],
        ),
        returnValue: _i6.Future<_i6.Stream<_i9.Uint8List>>.value(
            _i6.Stream<_i9.Uint8List>.empty()),
      ) as _i6.Future<_i6.Stream<_i9.Uint8List>>);

  @override
  _i6.Future<String?> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isRecording() => (super.noSuchMethod(
        Invocation.method(
          #isRecording,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> isPaused() => (super.noSuchMethod(
        Invocation.method(
          #isPaused,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i4.InputDevice>> listInputDevices() => (super.noSuchMethod(
        Invocation.method(
          #listInputDevices,
          [],
        ),
        returnValue:
            _i6.Future<List<_i4.InputDevice>>.value(<_i4.InputDevice>[]),
      ) as _i6.Future<List<_i4.InputDevice>>);

  @override
  _i6.Future<_i4.Amplitude> getAmplitude() => (super.noSuchMethod(
        Invocation.method(
          #getAmplitude,
          [],
        ),
        returnValue: _i6.Future<_i4.Amplitude>.value(_FakeAmplitude_3(
          this,
          Invocation.method(
            #getAmplitude,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Amplitude>);

  @override
  _i6.Future<bool> isEncoderSupported(_i4.AudioEncoder? encoder) =>
      (super.noSuchMethod(
        Invocation.method(
          #isEncoderSupported,
          [encoder],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<_i4.RecordState> onStateChanged() => (super.noSuchMethod(
        Invocation.method(
          #onStateChanged,
          [],
        ),
        returnValue: _i6.Stream<_i4.RecordState>.empty(),
      ) as _i6.Stream<_i4.RecordState>);

  @override
  _i6.Stream<_i4.Amplitude> onAmplitudeChanged(Duration? interval) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAmplitudeChanged,
          [interval],
        ),
        returnValue: _i6.Stream<_i4.Amplitude>.empty(),
      ) as _i6.Stream<_i4.Amplitude>);

  @override
  List<int> convertBytesToInt16(
    _i9.Uint8List? bytes, [
    dynamic endian = _i9.Endian.little,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertBytesToInt16,
          [
            bytes,
            endian,
          ],
        ),
        returnValue: <int>[],
      ) as List<int>);
}
